export const ASSETS_REQUEST_SUCCESS = "ASSETS_REQUEST_SUCCESS";
export const ASSETS_REQUEST_FAIL = "ASSETS_REQUEST_FAIL";
export const ASSETS_REQUEST_REQUEST = "ASSETS_REQUEST_REQUEST";
export const SINGLE_ASSET_SUCCESS = " SINGLE_ASSETS_SUCCESS";
export const SINGLE_ASSETS_FAIL = " SINGLE_ASSETS_FAIL";
export const SINGLE_ASSETS_REQUEST = " SINGLE_ASSETS_REQUEST";
