export const EXCHANGE_REQUEST_REQUEST = "EXCHANGE_REQUEST_REQUEST";
export const EXCHANGE_REQUEST_SUCCESS = "EXCHANGE_REQUEST_SUCCESS";
export const EXCHANGE_REQUEST_FAIL = "EXCHANGE_REQUEST_FAIL";
export const BITCOIN_REQUEST_REQUEST = "BITCOIN_REQUEST_REQUEST";
export const BITCOIN_REQUEST_SUCCESS = "BITCOIN_REQUEST_SUCCESS";
export const BITCOIN_REQUEST_FAIL = "BITCOIN_REQUEST_FAIL";
